[tool.poetry]
name = "trading-ml-bot"
version = "0.1.0"
description = ""
authors = ["sandipan <sandipan.bera94@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
